"""备注

Revision ID: f466ea7792a1
Revises: 
Create Date: 2019-05-02 11:43:08.650604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f466ea7792a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zj_heaven_for_user', 'new_openid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('zj_heaven_for_user', 'openid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zj_heaven_for_user', 'openid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('zj_heaven_for_user', 'new_openid',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
